name: Bug 错误
description: Report bugs 报告错误
labels: bug
body:
- type: input
  attributes:
    label: BKGalMgr version 程序版本
  validations:
    required: true
- type: input
  attributes:
    label: Windows version 系统版本
    placeholder: >
      win10 1904
  validations:
    required: true
- type: textarea
  attributes:
    label: Reproduction steps 复现步骤
    description: Describe the reproduction steps precisely if possible. 尽可能详细描述错误产生的细节。
  validations:
    required: true
